# requirements.yml
collections:
  - name: community.general
    version: 8.5.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.11.0
  - name: ansible.netcommon
    version: 5.3.0
  - name: cisco.nxos
    version: 5.3.0
  - name: https://github.com/CiscoDevNet/ansible-dcnm.git
    type: git
    version: develop
  # - name: https://github.com/netascode/ansible-dc-vxlan.git   # uncomment this item upon release
  #   type: git
  #   version: develop   # change version later
